markdown:      maruku
markdown_ext:  markdown,mkd,mkdn,md
pygments: true
permalink: /:title
rdiscount:
  extensions: [smart, Kramdown]
paginate: 10
name: PHP Programmers
url: http://blog.php-programmers.net
description: Blog of PHP-Programmers Community
twitter: #
github: phpprogrammers
facebook: #
mainSiteHome: http://blog.php-programmers.net
bannermain: banner_horizontal.jpg
author: Community author
authorUrl: http://php-programmers.net
fbAppId: 268051693301630
#gravatar_url: nil
